Areas/Admin/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaDeliveryManagement.Data;
using PizzaDeliveryManagement.Models;
using PizzaDeliveryManagement.Utility;

namespace PizzaDeliveryManagement.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticData.AdminUser)]
    [Area("Admin")]
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        [TempData]
        public string StatusMessage { get; set; }

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.Where(e=> e.Terminated==false).ToListAsync());
        }

        // GET: Admin/Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Admin/Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                //Checks if Employee has already been added by Admin.

                var checksIfLastNameExists = _context.Employees.FirstOrDefault(
                c => c.LastName == employee.LastName
             && c.LastName.ToLower().Contains(employee.LastName.ToLower())
             && c.FirstName == employee.FirstName
             && c.FirstName.ToLower().Contains(employee.FirstName.ToLower())

             );

                var terminatedEmployee = _context.Employees.Where(c=>c.FirstName == employee.FirstName
                && c.LastName == employee.LastName
                && c.Terminated == true).Any();

              
                  if (checksIfLastNameExists != null && terminatedEmployee == true)
                {

                    //Error
                    StatusMessage = "Error: Employee " + checksIfLastNameExists.FirstName + " " + checksIfLastNameExists.LastName + " has been terminated.";
                  
                }
                else if (checksIfLastNameExists != null)
                {
                    //Error
                    StatusMessage = "Error: Employee already in the system under " + checksIfLastNameExists.FirstName + " "
                        + checksIfLastNameExists.LastName;

                }
                else
                {
                    _context.Add(employee);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                
            }

            ViewBag.StatusMessage = StatusMessage;
            return View(employee);
        }

        // GET: Admin/Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Admin/Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Terminated")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //Checks if Employee has already been added by Admin.

                var checksIfLastNameExists = _context.Employees.FirstOrDefault(
                  c => c.LastName == employee.LastName
               && c.LastName.ToLower().Contains(employee.LastName.ToLower())
               && c.FirstName == employee.FirstName
               && c.FirstName.ToLower().Contains(employee.FirstName.ToLower())
               && c.Id != employee.Id

               );

                var terminatedEmployee = _context.Employees.Where(c => c.FirstName == employee.FirstName
                && c.LastName == employee.LastName
                && c.Terminated == true).Any();

                if (checksIfLastNameExists != null && terminatedEmployee == true)
                {

                    //Error
                    StatusMessage = "Error: Employee " + checksIfLastNameExists.FirstName + " " + checksIfLastNameExists.LastName + " has been terminated.";

                }
                else if (checksIfLastNameExists != null)
                {
                    //Error
                    StatusMessage = "Error: Employee already in the system under " + checksIfLastNameExists.FirstName + " "
                        + checksIfLastNameExists.LastName;

                }
                else
                {
                    try
                    {
                        _context.Update(employee);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!EmployeeExists(employee.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));

                }
               
            }
            ViewBag.StatusMessage = StatusMessage;
            return View(employee);
        }

        // GET: Admin/Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Admin/Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Controllers/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaDeliveryManagement.Data;
using PizzaDeliveryManagement.Models;
using PizzaDeliveryManagement.Utility;

namespace PizzaDeliveryManagement.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticData.AdminUser)]
    [Area("Admin")]
    public class SalariesController : Controller
    {
        private readonly ApplicationDbContext _context;
        [TempData]
        public string StatusMessage { get; set; }

        public SalariesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Salaries
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Salary.Include(s => s.Employee);
            return View(await applicationDbContext.Where(e=> e.Employee.Terminated == false).ToListAsync());
        }

        // GET: Admin/Salaries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary
                .Include(s => s.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // GET: Admin/Salaries/Create
        public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees.Where(e => e.Terminated == false), "Id", "FriendlyName");
            return View();
        }

        // POST: Admin/Salaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SalaryPerHour,EmployeeId")] Salary salary)
        {
            if (ModelState.IsValid)
            {

                //Checks if Employee already Has a Salary

                var checksEmployeeSalary = _context.Salary.Include(e => e.Employee).Where(e=> e.Employee.Id == salary.EmployeeId).Any();

                if(checksEmployeeSalary == true)
                {
                    //Error
                    StatusMessage = "Error : Employee already has salary in database. You can go and update it now";
                }
                else
                {
                    _context.Add(salary);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees.Where(e => e.Terminated == false), "Id", "FirstName", salary.EmployeeId);
            ViewBag.StatusMessage = StatusMessage;
            return View(salary);
        }

        // GET: Admin/Salaries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary.FindAsync(id);
            if (salary == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees.Where(e => e.Terminated == false && e.Id == salary.EmployeeId), "Id", "FriendlyName");
            return View(salary);
        }

        // POST: Admin/Salaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SalaryPerHour,EmployeeId")] Salary salary)
        {
            if (id != salary.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
               
                
                    try
                    {
                        _context.Update(salary);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!SalaryExists(salary.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
               
                
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees.Where(e => e.Terminated == false), "Id", "FriendlyName");
            ViewBag.StatusMessage = StatusMessage;
            return View(salary);
        }

        // GET: Admin/Salaries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary
                .Include(s => s.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // POST: Admin/Salaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var salary = await _context.Salary.FindAsync(id);
            _context.Salary.Remove(salary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaryExists(int id)
        {
            return _context.Salary.Any(e => e.Id == id);
        }
    }
}

Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PizzaDeliveryManagement.Data;
using PizzaDeliveryManagement.Helpers;
using PizzaDeliveryManagement.Models;

namespace PizzaDeliveryManagement.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CartController(ApplicationDbContext context)
        {
            _context = context;

        }
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Menu.Price * item.Quantity);
            return View();
        }

        private int isExist(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i< cart.Count; i++)
            {
                if (cart[i].Menu.MenuId.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        public IActionResult AddToCart(int id)
        {
            if(SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Menu = _context.Menu.SingleOrDefault(m=>m.MenuId == id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if(index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Menu = _context.Menu.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            _context.SaveChangesAsync();


            return RedirectToAction("Index");
        }

        public IActionResult Remove(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            _context.SaveChangesAsync();
            return RedirectToAction("index");

        }
    }
}

Areas/Customer/Controllers/ProductController.cs
using System;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PizzaDeliveryManagement.Data;

namespace PizzaDeliveryManagement.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
            
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Menu.Include(s=>s.PizzaSize).ToListAsync());
        }

     
    }
}

Views/Shared/_CreateBackButtonPartial.cshtml
<div class="row">
    <div class="col-xl-6 BottomSpace">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>

    <div class="col-xl-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>

</div>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-success"><i class="fas fa-plus"></i> &nbsp; Create New</a>
</p>

Views/Shared/_DeleteAndBackButton.cshtml
@model int

<div class="row">
    <div class="col-xl-6 BottomSpace">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-xl-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Views/Shared/_DetailsAndBackButton.cshtml
@model int

<div class="row">
    <div class="col-xl-6 BottomSpace">
        <a asp-action="Edit" class="btn btn-success form-control" asp-route-id="@Model">Edit</a>
    </div>
    <div class="col-xl-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Views/Shared/_EditBackButton.cshtml
@model int

<div class="row">
    <div class="col-xl-6 BottomSpace">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
    </div>
    <div class="col-xl-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using PizzaDeliveryManagement.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaDeliveryManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>


    @if (User.IsInRole(StaticData.AdminUser))
    {
        <nav class="navbar navbar-expand-md fixed-top">
            <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">Pizza Delivery</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown text-white-50">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage Here!
                        </a>
                        <ul class="dropdown-menu dropdown-bg" aria-labelledby="navbarDropDownMenuLink">

                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle text-success font-weight-bold h5" href="#">
                                    Employees
                                </a>
                                <ul class="dropdown-menu dropdown-bg">
                                    <li><a class="dropdown-item text-success font-weight-bold" asp-action="Index" asp-controller="Employees" asp-area="Admin"><span style="text-transform:uppercase">Employees' List</span></a></li>
                                    <li><a class="dropdown-item text-success font-weight-bold" asp-action="Index" asp-controller="Salaries" asp-area="Admin"><span style="text-transform:uppercase">Employees Salary</span></a></li>
                                </ul>
                            </li>
                            <li><a class="dropdown-item text-success font-weight-bold" asp-action="" asp-controller="" asp-area="Admin"><span style="text-transform:uppercase">Customers</span></a></li>
                            <li><a class="dropdown-item text-success font-weight-bold" asp-action="" asp-controller="" asp-area="Admin"><span style="text-transform:uppercase">Orders</span></a></li>
                        </ul>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
                
            </div>

        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-md fixed-top">
            <a class="navbar-brand" asp-area="Customer" asp-controller="Product" asp-action="Index">Pizza Delivery</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>

        </nav>
    }


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PizzaDeliveryManagement - <a href="https://github.com/Rbeninche/Pizza-Delivery-Mngt" target="_blank">Github</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PCart.cshtml
<ul class="navbar-nav">
    <li class="nav-item">

        <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index" id="cartItem">Cart</a>
    </li>
</ul>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TableButton.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-user-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-info-circle"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-minus-circle"></i>
        </a>
    </div>
</td>